#!/bin/sh

SOURCE="assets"
OUT="assets.zip"

if [ -d "$SOURCE" ]; then
    if [ -f "$OUT" ]; then
        rm "$OUT"
    fi

    PREV_DIR="$(pwd)"

    cd "$SOURCE" || exit 1
    rm -f "$PREV_DIR/$OUT"
    zip -r "$PREV_DIR/$OUT" . -x "*.DS_Store"
    cd "$PREV_DIR" || exit 1

    echo "Compiled sources at $SOURCE to $OUT"
else
    echo "Error! Sources at $SOURCE do not exist"
    exit 1
fi

if [ -d ".git" ]; then
    git add "$OUT"
fi