#!/bin/sh

SOURCE="assets/"
OUT="assets.zip"

if [ -d "$SOURCE" ]; then
	zip -r -j assets.zip $SOURCE
	echo "Compiled sources at $SOURCE to $OUT"
else
    echo "Error! Sources at $SOURCE do not exist"
    exit 1
fi

if [ -d ".git" ]; then
    git add assets.zip
fi