include "#!./gradlew -q printConveyorConfig"

app {
  display-name = "Floorcraft"
  fsname = "floorcraft"
  icons = "src/main/resources/icon.png"
  rdns-name = "com.boyninja1555.floorcraft"
  vcs-url = "github.com/boyninja1555/floorcraft"

  inputs += "build/libs/Floorcraft-*.jar"

  jvm {
    gui.main-class = "com.boyninja1555.floorcraft.Floorcraft"
    flags = ["--enable-native-access=ALL-UNNAMED"]
  }

  commands += {
		name = "floorcraft"
	}

	windows {
		file-associations += {
			extension = "fcraftmod"
			name = "Floorcraft Mod"
			description = "Installable file containing modified assets for Floorcraft"
			mime-type = "application/x-floorcraft-mod"
		}
	}

  mac {
		jvm.flags += "-XstartOnFirstThread"
		file-associations += {
			extension = "fcraftmod"
			name = "Floorcraft Mod"
			description = "Installable file containing modified assets for Floorcraft"
			mime-type = "application/x-floorcraft-mod"
		}
	}

	linux {
		file-associations += {
			extension = "fcraftmod"
			name = "Floorcraft Mod"
			description = "Installable file containing modified assets for Floorcraft"
			mime-type = "application/x-floorcraft-mod"
		}
	}

  machines = ["win", "linux", "mac"]

  site {
  	base-url = "https://floorcrafting.github.io/floorcraft/"
  	consistency-checks = "warn"
  }
}

conveyor.compatibility-level = 21