#!/bin/sh
set -e
./prepackage
./conveyor make site --overwrite
echo "Floorcraft built! Note this build is a website intended for downloading the game."
printf "%s" "Press Enter to publish the site..."
read ans
rm -rf docs
mkdir docs
cp -r output/* docs/
git add docs
git commit -m "Update download website $RANDOM-$RANDOM-$RANDOM"
git push